//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mjml.Net.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mjml.Net.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!--[if mso]&gt;
        ///        &lt;noscript&gt;
        ///        &lt;xml&gt;
        ///        &lt;o:OfficeDocumentSettings&gt;
        ///          &lt;o:AllowPNG/&gt;
        ///          &lt;o:PixelsPerInch&gt;96&lt;/o:PixelsPerInch&gt;
        ///        &lt;/o:OfficeDocumentSettings&gt;
        ///        &lt;/xml&gt;
        ///        &lt;/noscript&gt;
        ///        &lt;![endif]--&gt;
        ///  &lt;!--[if lte mso 11]&gt;
        ///        &lt;style type=&quot;text/css&quot;&gt;
        ///          .mj-outlook-group-fix { width:100% !important; }
        ///        &lt;/style&gt;
        ///        &lt;![endif]--&gt;.
        /// </summary>
        internal static string DefaultComments {
            get {
                return ResourceManager.GetString("DefaultComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!--[if !mso]&gt;&lt;!--&gt;
        ///&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;
        ///&lt;!--&lt;![endif]--&gt;
        ///&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        ///&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot;&gt;.
        /// </summary>
        internal static string DefaultMeta {
            get {
                return ResourceManager.GetString("DefaultMeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #outlook a {
        ///  padding: 0;
        ///}
        ///
        ///body {
        ///  margin: 0;
        ///  padding: 0;
        ///  -webkit-text-size-adjust: 100%;
        ///  -ms-text-size-adjust: 100%;
        ///}
        ///
        ///table,
        ///td {
        ///  border-collapse: collapse;
        ///  mso-table-lspace: 0pt;
        ///  mso-table-rspace: 0pt;
        ///}
        ///
        ///img {
        ///  border: 0;
        ///  height: auto;
        ///  line-height: 100%;
        ///  outline: none;
        ///  text-decoration: none;
        ///  -ms-interpolation-mode: bicubic;
        ///}
        ///
        ///p {
        ///  display: block;
        ///  margin: 13px 0;
        ///}.
        /// </summary>
        internal static string DefaultStyles {
            get {
                return ResourceManager.GetString("DefaultStyles", resourceCulture);
            }
        }
    }
}
