//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!doctype html&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; xmlns:v=&quot;urn:schemas-microsoft-com:vml&quot; xmlns:o=&quot;urn:schemas-microsoft-com:office:office&quot;&gt;
        ///
        ///&lt;head&gt;
        ///  &lt;title&gt;
        ///  &lt;/title&gt;
        ///  &lt;!--[if !mso]&gt;&lt;!--&gt;
        ///  &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;
        ///  &lt;!--&lt;![endif]--&gt;
        ///  &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        ///  &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot;&gt;
        ///  &lt;style type=&quot;text/css&quot;&gt;
        ///    #outlook a {
        ///      padding: 0;
        ///    }
        ///
        ///    body {        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BodyOnly {
            get {
                return ResourceManager.GetString("BodyOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;style type=&quot;text/css&quot;&gt;
        ///  @media only screen and (min-width:300px) {
        ///    .mj-column-per-100 {
        ///      width: 100% !important;
        ///      max-width: 100%;
        ///    }
        ///  }
        ///&lt;/style&gt;
        ///&lt;style media=&quot;screen and (min-width:300px)&quot;&gt;
        ///  .moz-text-html .mj-column-per-100 {
        ///    width: 100% !important;
        ///    max-width: 100%;
        ///  }
        ///&lt;/style&gt;.
        /// </summary>
        internal static string Breakpoint {
            get {
                return ResourceManager.GetString("Breakpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p style=&quot;display:inline-block;background:#f45e43;color:white;font-family:Helvetica;font-weight:normal;line-height:120%;margin:0;text-decoration:none;text-transform:none;padding:10px 25px;mso-padding-alt:0px;text-align:center;border-radius:3px;&quot;&gt;
        ///Button
        ///&lt;/p&gt;.
        /// </summary>
        internal static string Button {
            get {
                return ResourceManager.GetString("Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href=&quot;https://mjml.io/&quot; target=&quot;_blank&quot; style=&quot;display:inline-block;background:#f45e43;color:white;font-family:Helvetica;font-weight:normal;line-height:120%;margin:0;text-decoration:none;text-transform:none;padding:10px 25px;mso-padding-alt:0px;text-align:center;border-radius:3px;&quot;&gt;
        ///Button Link
        ///&lt;/a&gt;.
        /// </summary>
        internal static string ButtonLink {
            get {
                return ResourceManager.GetString("ButtonLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!--[if !mso]&gt;&lt;!--&gt;
        ///&lt;link href=&quot;https://fonts.googleapis.com/css?family=Raleway&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot;&gt;
        ///&lt;style type=&quot;text/css&quot;&gt;
        ///  @import url(https://fonts.googleapis.com/css?family=Raleway);
        ///&lt;/style&gt;
        ///&lt;!--&lt;![endif]--&gt;.
        /// </summary>
        internal static string Font {
            get {
                return ResourceManager.GetString("Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div style=&quot;display:none;font-size:1px;color:#ffffff;line-height:1px;max-height:0px;max-width:0px;opacity:0;overflow:hidden;&quot;&gt;
        ///  Hello MJML
        ///&lt;/div&gt;.
        /// </summary>
        internal static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div style=&quot;height:20px;line-height:20px;&quot;&gt;
        ///  &amp;#8202;
        ///&lt;/div&gt;.
        /// </summary>
        internal static string Spacer {
            get {
                return ResourceManager.GetString("Spacer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div style=&quot;height:100px;line-height:100px;&quot;&gt;
        ///  &amp;#8202;
        ///&lt;/div&gt;.
        /// </summary>
        internal static string SpacerWithHeight {
            get {
                return ResourceManager.GetString("SpacerWithHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;style type=&quot;text/css&quot;&gt;
        ///  .red-text div {
        ///    color: red !important;
        ///  }
        ///&lt;/style&gt;.
        /// </summary>
        internal static string Style {
            get {
                return ResourceManager.GetString("Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;title&gt;
        ///  Hello MJML
        ///&lt;/title&gt;.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
