using System.Globalization;
using Grynwald.MarkdownGenerator;

namespace Mjml.Net.Compare;

public static class MarkdownReport
{
    private const string Command = "dotnet run -c Release --project Mjml.Net.Compare";

    public static string BuildDetails(Comparison comparison)
    {
        var machine = comparison.Machine;

        var document = new MdDocument(
            new MdHeading(1, "Mjml.Net vs. MJML (JavaScript)"),
            new MdBlockQuote(new MdParagraph("Generated by ", new MdCodeSpan(Command), ". Do not edit manually.")),
            new MdParagraph(
                "Both renderers run in-process (no process startup, no disk I/O inside the measured loop) on the templates in ",
                new MdCodeSpan("Mjml.Net.Benchmark/Templates"),
                ". Beautify and minify are disabled and MJML validation is skipped on both sides, so only the rendering itself is measured. ",
                $"Before measuring, all templates are rendered {comparison.Warmup} times so that the .NET JIT and V8 have optimized all code paths."),
            new MdParagraph(
                new MdEmphasisSpan("First"),
                " is the time of the very first (cold) render of each template; for the first template this includes JIT compilation and module loading. ",
                new MdEmphasisSpan("Speedup"),
                " is ",
                new MdCodeSpan("JS Median / .NET Median"),
                "."),
            new MdHeading(2, "Environment"),
            new MdTable(
                new MdTableRow("Item", "Value"),
                new MdTableRow("Date", FormatDate(comparison)),
                new MdTableRow("OS", machine.Os),
                new MdTableRow("CPU", $"{machine.Cpu} ({machine.Cores} logical cores)"),
                new MdTableRow("Mjml.Net", $"{machine.MjmlNetVersion} on .NET {machine.DotNetVersion}"),
                new MdTableRow("MJML (JS)", $"{comparison.Js.MjmlVersion} on Node.js {comparison.Js.NodeVersion}"),
                new MdTableRow("Iterations", $"{comparison.Iterations} per template (after {comparison.Warmup} warmup rounds)")),
            new MdHeading(2, "Summary"),
            new MdBulletList(
                new MdListItem(new MdParagraph("Geometric mean speedup: ", new MdStrongEmphasisSpan($"{Fmt(comparison.SpeedupGeoMean)}x"))),
                new MdListItem(new MdParagraph($"Speedup range: {Fmt(comparison.SpeedupMin)}x - {Fmt(comparison.SpeedupMax)}x")),
                new MdListItem(new MdParagraph(
                    "All templates once (sum of medians): Mjml.Net ",
                    new MdStrongEmphasisSpan($"{Fmt(comparison.TotalNetMs)} ms"),
                    ", MJML (JS) ",
                    new MdStrongEmphasisSpan($"{Fmt(comparison.TotalJsMs)} ms")))),
            new MdHeading(2, "Results"),
            new MdParagraph("All times in milliseconds."),
            BuildResultsTable(comparison));

        return document.ToString(MinimalTextFormatter.Options);
    }

    public static string BuildSummary(Comparison comparison)
    {
        var machine = comparison.Machine;

        var document = new MdDocument(
            new MdHeading(3, "Mjml.Net vs. MJML (JavaScript)"),
            new MdParagraph(
                $"Rendering the {comparison.Rows.Count} benchmark templates in-process, Mjml.Net {machine.MjmlNetVersion} (.NET {machine.DotNetVersion}) is on average ",
                new MdStrongEmphasisSpan($"{Fmt(comparison.SpeedupGeoMean)}x faster"),
                $" than MJML {comparison.Js.MjmlVersion} (Node.js {comparison.Js.NodeVersion}), with speedups between {Fmt(comparison.SpeedupMin)}x and {Fmt(comparison.SpeedupMax)}x per template."),
            new MdTable(
                new MdTableRow("Renderer", "All templates (sum of medians)"),
                new MdTableRow($"Mjml.Net {machine.MjmlNetVersion}", $"{Fmt(comparison.TotalNetMs)} ms"),
                new MdTableRow($"MJML {comparison.Js.MjmlVersion} (JS)", $"{Fmt(comparison.TotalJsMs)} ms")),
            new MdParagraph(
                $"Measured on {machine.Cpu}, {FormatDate(comparison)}. See ",
                new MdLinkSpan("benchmark.md", "benchmark.md"),
                " for the results per template. Run ",
                new MdCodeSpan(Command),
                " to reproduce."));

        return document.ToString(MinimalTextFormatter.Options);
    }

    private static MdTable BuildResultsTable(Comparison comparison)
    {
        var tableHeader = new MdTableRow(
            "Template",
            ".NET Median",
            ".NET Mean",
            ".NET P95",
            ".NET First",
            ".NET Allocated",
            "JS Median",
            "JS Mean",
            "JS P95",
            "JS First",
            "Speedup");

        var tableRows = comparison.Rows.Select(row => new MdTableRow(
            row.Net.Template,
            Fmt(row.Net.Median),
            Fmt(row.Net.Mean),
            Fmt(row.Net.P95),
            Fmt(row.Net.FirstMs),
            $"{Fmt(row.Net.AllocatedBytes / 1024d, "N0")} KB",
            Fmt(row.Js.Median),
            Fmt(row.Js.Mean),
            Fmt(row.Js.P95),
            Fmt(row.Js.FirstMs),
            new MdStrongEmphasisSpan($"{Fmt(row.Speedup)}x")));

        return new MdTable(tableHeader, tableRows);
    }

    private static string FormatDate(Comparison comparison)
    {
        return comparison.Date.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture);
    }

    private static string Fmt(double value, string format = "N2")
    {
        return value.ToString(format, CultureInfo.InvariantCulture);
    }
}
